### ISSUE TITLE
Resolution of preview image is bad

### ISSUE THREAD

**Issue by tdapper** [Thicket-Blender/thicket#29]
The preview image (in both, browser and property editor) currently is really low resolution. That doesn't look good and also makes it hard to make out details that may be helpful to consider when picking a plant in the browser.

**Comment by dvhart** [comment]
Thanks for reporting this issue.

This is one of the many areas where I have found the Blender UI toolkit to be frustratingly rigid and limiting. The current mechanism uses a scaled icon, so while the source image is the higher resolution preview shipped by Laubwerk with the Plant Kits, the Blender preview/icon mechanism scales it down to be used as an icon, and then we scale it back up to use it as a preview. It's an admittedly bad solution.

The solutions I've explored on the Blender development forums to improve the image quality have other limitations which I found to be worse tradeoffs than the image resolution.

So this needs to be addressed, but I don't yet know how we can address it. Marking as an enhancement and we will continue to work with the Blender dev community to find a better solution.

**Comment by dvhart** [comment]
I've kept digging for a better solution, and there just does not appear to be anything we can use in the UI from Python that will show the full resolution image, rather than a scaled icon. Even the "blender way" using template_icon_view shows the same pixelation (and indeed, you pass it an icon_id). Also.... it's a ****terrible widget**** wow!

![Uploading Screen Shot 2020-11-19 at 10.36.11 PM.png…]()
