### ISSUE TITLE
"Failed to load Laubwerk Python Extension from this path"

### ISSUE THREAD

**Issue by Triforceguard** [Thicket-Blender/thicket#51]
Error Message when selecting Python path. Using thicket 0.4.0 and freshly installed Laubwerk libraries (LaubwerkPlantsKit2 ,LaubwerkPlantsKit8, & LaubwerkPlantsKitFreebie, version 1.034)

![image](https://user-images.githubusercontent.com/87174092/125047526-5c6cfb00-e09f-11eb-9fcf-3d9871121a92.png)

Same issue on 2 different PCs

 - OS: Windows 10
 - OS 20H2
 - Blender Version: 2.93.1
 - Blender Version: 2.83.4

**Comment by dvhart** [comment]
Thanks for reporting. When you installed the Laubwerk plants kit, did you follow the installation step in the Thicket README regarding the Python Extension:

“Choose the "Custom" installation method and ensure the "Python Extension" component is checked.”

**Comment by Triforceguard** [comment]
Thank you for your quick reply,
I've tried it several more times on both computers, however I had no luck.
The "Python" Folder itself exists and has files inside.

**Comment by dvhart** [comment]
It sounds like you have found a new issue. I will try and reproduce on my Windows VM. If you are able to launch Blender from the command line and share the log, that may help pinpoint what is going on. A recursive directory listing of Laubwerk/Python may be informative as well. The only other thing I can suggest to try while I try to reproduce this would be to upgrade to the latest Laubwerk Plant Kit version (1.0.37, the Freebie is sufficient to get the Python binding) - but I don't expect that to help since you are running a tested version. I'll follow up here when I can reproduce the issue.

**Comment by Triforceguard** [comment]
They've updated to 1.0.38, I've tried it with this version and it worked immediately. Thanks again for your fast responses!
